### ISSUE TITLE
Cargo Watch Doesn't recompile changes automatically..

### ISSUE THREAD

**Issue by jazib-bashir** [JasterV/actix-web-posts-api#3]
I'm following your tutorial to implement articles API but in my case `cargo watch` doesn't listen for changes. I have tried different IDE for this (VS code, IntelliJ IDEA).

Are you using any kind of configuration?

Thanks,
Jazib BASHIR

**Comment by JasterV** [comment]
Cargo watch runs 'cargo check' by default if you don't specify anything else, in order to get it to build the project each time you make a change you must run "cargo watch -x build", or "cargo watch -x run" if you want to build and run each time

**Comment by JasterV** [comment]
Btw notice that I'm using docker to run the application, if something is not running for you I suggest to check the Dockerfiles and docker-compose files to see if you have any environment variable missing ^^

**Comment by jazib-bashir** [comment]
Thanks for you reply!
I'm also using docker environment with the same configurations as you have in you repo. I also installed your project locally and test `cargo watch` and `cargo watch -x run` on it. same issue.

**Comment by JasterV** [comment]
Also, notice that if you do not "use" the files on the main binary/library, they wont get compiled, so maybe there is the problem ^^

**Comment by jazib-bashir** [comment]
Hi @JasterV  🙂 
Hope you'r doing well.

This issue is fixed. The issue was related to docker version. Previously i was using docker version `20` and now i'm using `19.03.13`

Thanks
